"use client"
import { useState, Children, cloneElement, useEffect } from 'react'
import './globals.css'
import Login from './login'
import Sidebar from './components/Sidebar'
import { supabase } from '../utils/supabaseClient'
import { AuthContextProvider } from './context'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}